package random

import "strings"

func (p *Patient) PhoneNumber() *Patient {
	city := p.PatientAddress.RegionInfo.City

	regionAreaCode := AreaCode(city)

	phoneNumber := regionAreaCode + "1234567"

	p.Phone = phoneNumber

	return p
}

func AreaCode(city string) string {
	areaCodeByCity := map[string]string{
		"MOBILE":           "251",
		"MONTGOMERY":       "334",
		"BIRMINGHAM":       "205",
		"ANCHORAGE":        "907",
		"JUNEAU":           "907",
		"FAIRBANKS":        "907",
		"PHOENIX":          "602",
		"TUCSON":           "520",
		"MESA":             "480",
		"LITTLE ROCK":      "501",
		"FAYETTEVILLE":     "479",
		"SPRINGDALE":       "479",
		"LOS ANGELES":      "213",
		"SAN DIEGO":        "619",
		"SAN JOSE":         "408",
		"DENVER":           "303",
		"COLORADO SPRINGS": "719",
		"BRIDGEPORT":       "203",
		"STAMFORD":         "203",
		"NEW HAVEN":        "203",
		"WILMINGTON":       "302",
		"DOVER":            "302",
		"WASHINGTON DC":    "202",
		"JACKSONVILLE":     "904",
		"MIAMI":            "305",
		"TAMPA":            "813",
		"ATLANTA":          "404",
		"AUGUSTA":          "706",
		"HONOLULU":         "808",
		"PEARL CITY":       "808",
		"HILO":             "808",
		"BOISE":            "208",
		"MERIDIAN":         "208",
		"NAMPA":            "208",
		"CHICAGO":          "312",
		"AURORA":           "630",
		"NAPERVILLE":       "630",
		"INDIANAPOLIS":     "317",
		"FORT WAYNE":       "260",
		"EVANSVILLE":       "812",
		"DES MOINES":       "515",
		"CEDAR RAPIDS":     "319",
		"DAVENPORT":        "563",
		"WICHITA":          "316",
		"OVERLAND PARK":    "913",
		"LOUISVILLE":       "502",
		"LEXINGTON":        "859",
		"BOWLING GREEN":    "270",
		"NEW ORLEANS":      "504",
		"BATON ROUGE":      "225",
		"SHERVEPORT":       "318",
		"BANGOR":           "207",
		"LEWISTON":         "207",
		"BALTIMORE":        "410",
		"GERMANTOWN":       "301",
		"BOSTON":           "617",
		"WORCESTER":        "508",
		"DETROIT":          "313",
		"GRAND RAPIDS":     "616",
		"WARREN":           "586",
		"MINNEAPOLIS":      "612",
		"SAINT PAUL":       "651",
		"ROCHESTER":        "507",
		"JACKSON":          "601",
		"GULFPORT":         "228",
		"SOUTHAVEN":        "662",
		"KANSAS CITY":      "816",
		"SAINT LOUIS":      "314",
		"SPRINGFIELD":      "417",
		"BILLINGS":         "406",
		"MISSOULA":         "406",
		"GREAT FALLS":      "406",
		"OMAHA":            "402",
		"LINCOLN":          "402",
		"BELLEVUE":         "402",
		"LAS VEGAS":        "702",
		"HENDERSON":        "702",
		"RENO":             "775",
		"MANCHESTER":       "603",
		"NASHUA":           "603",
		"CONCORD":          "603",
		"NEWARK":           "973",
		"JERSEY CITY":      "201",
		"PATERSON":         "973",
		"ALBUQUERQUE":      "505",
		"LAS CRUCES":       "575",
		"SANTA FE":         "505",
		"NEW YORK CITY":    "212",
		"BUFFALO":          "716",
		"YONKERS":          "914",
		"CHARLOTTE":        "704",
		"RALEIGH":          "919",
		"GREENSBORO":       "336",
		"FARGO":            "701",
		"BISMARK":          "701",
		"GRAND FORKS":      "701",
		"COLUMBUS":         "614",
		"CLEVELAND":        "216",
		"CINCINNATI":       "513",
		"OKLAHOMA CITY":    "405",
		"TULSA":            "918",
		"NORMAN":           "405",
		"PORTLAND":         "503",
		"SALEM":            "503",
		"EUGENE":           "541",
		"PHILADELPHIA":     "215",
		"PITTSBURGH":       "412",
		"ALLENTOWN":        "610",
		"PROVIDENCE":       "401",
		"CRANSTON":         "401",
		"WARWICK":          "401",
		"COLUMBIA":         "803",
		"MOUNT PLEASANT":   "843",
		"SIOUX FALLS":      "605",
		"RAPID CITY":       "605",
		"ABERDEEN":         "605",
		"NASHVILLE":        "615",
		"MEMPHIS":          "901",
		"KNOXVILLE":        "865",
		"DALLAS":           "214",
		"HOUSTON":          "713",
		"AUSTIN":           "512",
		"SALT LAKE CITY":   "801",
		"PROVO":            "385",
		"WEST JORDAN":      "385",
		"BURLINGTON":       "802",
		"COLCHESTER":       "802",
		"RUTLAND":          "802",
		"VIRGINIA BEACH":   "757",
		"NORFOLK":          "757",
		"RICHMOND":         "804",
		"SEATTLE":          "206",
		"SPOKANE":          "509",
		"TACOMA":           "253",
		"CHARLESTON":       "304",
		"HUNTINGTON":       "304",
		"MORGANTOWN":       "304",
		"MILWAUKEE":        "414",
		"MADISON":          "608",
		"GREEN BAY":        "920",
		"CHEYENNE":         "307",
		"CASPER":           "307",
		"LARAMIE":          "307"}

	for k, v := range areaCodeByCity {
		if strings.Contains(k, city) {
			return v
		}
	}

	return ""
}
