package sugarpill

import (
	"encoding/json"
	"reflect"
	"strings"

	"github.com/hl7x/placebo/pkg/message"
	"github.com/hl7x/placebo/pkg/random"
)

type HL7Message struct {
	MSH *MSH `json:"MSH"`
	EVN *EVN `json:"EVN"`
	PID *PID `json:"PID"`
	PD1 *PD1 `json:"PD1"`
	ROL *ROL `json:"ROL"`
	DB1 *DB1 `json:"DB1"`
	ARV *ARV `json:"ARV"`
	NK1 *NK1 `json:"NK1"`
	PV1 *PV1 `json:"PV1"`
	PV2 *PV2 `json:"PV2"`
	GT1 *GT1 `json:"GT1"`
	IN1 *IN1 `json:"IN1"`
	AL1 *AL1 `json:"AL1"`
	DG1 *DG1 `json:"DG1"`
	SCH *SCH `json:"SCH"`
	RF1 *RF1 `json:"RF1"`
	TXA *TXA `json:"TXA"`
	ORC *ORC `json:"ORC"`
	OBR *OBR `json:"OBR"`
	NTE *NTE `json:"NTE"`
	OBX *OBX `json:"OBX"`
}

// SegmentOrder is every segment placebo knows, in the order a message carries
// them. Rendering walks this list, so whichever subset a message holds comes
// out in a stable order.
var SegmentOrder = []string{
	"MSH", "EVN", "PID", "PD1", "ROL", "DB1", "ARV", "NK1",
	"PV1", "PV2", "GT1", "IN1", "AL1", "DG1",
	"SCH", "RF1", "TXA", "ORC", "OBR", "NTE", "OBX",
}

// DefaultLayout is what placebo builds when no message type has narrowed the
// segments down. It leaves out the segments that define one specific message
// type - a referral and a document notification have no business in the same
// message - but is otherwise broad, since the interactive sugarpill flow
// hands the result over to be edited and a segment left out is one the person
// editing cannot put back.
var DefaultLayout = []string{
	"MSH", "EVN", "PID", "PD1", "ROL", "DB1", "ARV", "NK1",
	"PV1", "PV2", "GT1", "IN1", "AL1", "DG1",
	"ORC", "OBR", "NTE", "OBX",
}

func NewHL7Message(p *random.Patient) *HL7Message {
	return NewLayoutMessage(p, DefaultLayout)
}

// NewLayoutMessage builds only the segments named in layout. A message type
// carries the segments its trigger event is defined around and no others, so
// the layout is what separates an order message from an admit.
func NewLayoutMessage(p *random.Patient, layout []string) *HL7Message {

	message := &HL7Message{}

	for _, name := range layout {
		segment := NewSegment(name, p)
		if segment == nil {
			continue
		}

		message.SegmentAssigner(segment)
	}

	return message
}

// NewHL7EventMessage builds a message of one type and trigger event, laid out
// with the segments that type carries.
func NewHL7EventMessage(p *random.Patient, t string, e string, layout []string) string {

	message := NewLayoutMessage(p, layout)

	message.ApplyEvent(p, t, e)

	return MessageBuilderFor(message, layout)
}

// ApplyEvent stamps a message type and trigger event onto the segments that
// carry them, so the segments agree with each other rather than each claiming
// a different event. Segments built generically are also narrowed to what the
// message type means: the same OBX reports a lab value in a result message
// and a line of a note in a document notification.
func (msg *HL7Message) ApplyEvent(p *random.Patient, t string, e string) *HL7Message {

	if msg.MSH != nil && msg.MSH.MessageType != nil {
		msg.MSH.MessageType.MessageCode = t
		msg.MSH.MessageType.TriggerEvent = e
	}

	// EVN-1 is the trigger event, not the message code: an admit records
	// A01 here, not ADT.
	if msg.EVN != nil {
		msg.EVN.EventTypeCode = e
	}

	switch t {

	case "ORM":
		// An order is a request for a result that does not exist yet, so
		// there is no result status to report on it.
		if msg.OBR != nil {
			msg.OBR.ResultStatus = ""
		}

	case "ORU":
		// Results travel against an order that already exists, so the
		// order control code reports an observation rather than a new
		// request.
		if msg.ORC != nil {
			msg.ORC.OrderControl = "RE"
		}

	case "MDM":
		// A document notification carries note text in OBX, not the
		// numeric lab value OBX is built with.
		if msg.OBX != nil {
			msg.OBX.ValueType = "TX"
			msg.OBX.ObservationIdentifier = p.Document.Type.Code + "^" + p.Document.Type.Name
			msg.OBX.ObservationValue = p.Document.Type.Name + " GENERATED BY PLACEBO FOR TESTING"
			msg.OBX.Units = &ServiceCode{}
			msg.OBX.ReferencesRange = ""
			msg.OBX.AbnormalFlags = ""
		}
	}

	return msg
}

// NewSegment builds the named segment for a patient, or nil when placebo does
// not know how to build that segment.
func NewSegment(name string, p *random.Patient) interface{} {

	switch name {
	case "MSH":
		return NewMSHSegment(p)
	case "EVN":
		return NewEVNSegment(p)
	case "PID":
		return NewPIDSegment(p)
	case "PD1":
		return NewPD1Segment(p)
	case "ROL":
		return NewROLSegment(p)
	case "DB1":
		return NewDB1Segment(p)
	case "ARV":
		return NewARVSegment(p)
	case "NK1":
		return NewNK1Segment(p)
	case "PV1":
		return NewPV1Segment(p)
	case "PV2":
		return NewPV2Segment(p)
	case "GT1":
		return NewGT1Segment(p)
	case "IN1":
		return NewIN1Segment(p)
	case "AL1":
		return NewAL1Segment(p)
	case "DG1":
		return NewDG1Segment(p)
	case "SCH":
		return NewSCHSegment(p)
	case "RF1":
		return NewRF1Segment(p)
	case "TXA":
		return NewTXASegment(p)
	case "ORC":
		return NewORCSegment(p)
	case "OBR":
		return NewOBRSegment(p)
	case "NTE":
		return NewNTESegment(p)
	case "OBX":
		return NewOBXSegment(p)
	default:
		return nil
	}
}

func (m *HL7Message) MessageToJson() string {

	message, err := json.MarshalIndent(m, "", " ")
	if err != nil {
		panic(err)
	}

	return string(message)
}

func JsonToMessage(s string) *HL7Message {
	jsonMessage := []byte(s)

	var msg *HL7Message
	err := json.Unmarshal(jsonMessage, &msg)
	if err != nil {
		panic(err)
	}

	return msg
}

func (msg *HL7Message) ReadFromFile(s string) *HL7Message {
	lines := LinesFromFile(s)

	for _, line := range lines {
		segs := strings.Split(line, "|")
		segType := SegmentFinder(segs[0])
		onlyMessageSegs := segs[1:]
		bind := message.MarshallHL7(onlyMessageSegs, segType)
		msg.SegmentAssigner(bind)
	}

	return msg
}

func ReadHL7(content string) string {

	messageStruct := &HL7Message{}
	msg := messageStruct.ReadFromFile(content)

	messageFmt, _ := json.MarshalIndent(msg, "", " ")

	jsonMessage := SanitizeLines(string(messageFmt))

	return jsonMessage
}

func SegmentFinder(s string) interface{} {

	switch s {
	case "MSH":
		return &MSH{}
	case "EVN":
		return &EVN{}
	case "PID":
		return &PID{}
	case "PD1":
		return &PD1{}
	case "ROL":
		return &ROL{}
	case "DB1":
		return &DB1{}
	case "ARV":
		return &ARV{}
	case "NK1":
		return &NK1{}
	case "PV1":
		return &PV1{}
	case "PV2":
		return &PV2{}
	case "GT1":
		return &GT1{}
	case "IN1":
		return &IN1{}
	case "AL1":
		return &AL1{}
	case "DG1":
		return &DG1{}
	case "SCH":
		return &SCH{}
	case "RF1":
		return &RF1{}
	case "TXA":
		return &TXA{}
	case "ORC":
		return &ORC{}
	case "OBR":
		return &OBR{}
	case "NTE":
		return &NTE{}
	case "OBX":
		return &OBX{}
	default:
		return nil
	}
}

func (msg *HL7Message) SegmentAssigner(s interface{}) *HL7Message {

	switch v := s.(type) {
	case *MSH:
		msg.MSH = v
	case *EVN:
		msg.EVN = v
	case *PID:
		msg.PID = v
	case *PD1:
		msg.PD1 = v
	case *ROL:
		msg.ROL = v
	case *DB1:
		msg.DB1 = v
	case *ARV:
		msg.ARV = v
	case *NK1:
		msg.NK1 = v
	case *PV1:
		msg.PV1 = v
	case *PV2:
		msg.PV2 = v
	case *GT1:
		msg.GT1 = v
	case *IN1:
		msg.IN1 = v
	case *AL1:
		msg.AL1 = v
	case *DG1:
		msg.DG1 = v
	case *SCH:
		msg.SCH = v
	case *RF1:
		msg.RF1 = v
	case *TXA:
		msg.TXA = v
	case *ORC:
		msg.ORC = v
	case *OBR:
		msg.OBR = v
	case *NTE:
		msg.NTE = v
	case *OBX:
		msg.OBX = v
	default:
		return nil
	}

	return msg
}

// Segment returns the named segment, or nil when the message does not carry
// one. A message built for a message type holds only that type's segments, so
// the absent ones have to be distinguishable from the empty ones.
func (msg *HL7Message) Segment(name string) interface{} {

	field := reflect.ValueOf(msg).Elem().FieldByName(name)

	if !field.IsValid() || field.IsNil() {
		return nil
	}

	return field.Interface()
}

// MessageBuilder renders every segment the message carries. Used where the
// message came back from JSON rather than from a message type, so what it
// holds is whatever the person editing it left behind.
func MessageBuilder(msg *HL7Message) string {
	return MessageBuilderFor(msg, SegmentOrder)
}

// MessageBuilderFor renders the segments named in layout, in that order. A
// segment the message does not carry is left out rather than sent empty,
// which is what keeps an order message from arriving with an insurance
// segment stapled to it.
func MessageBuilderFor(msg *HL7Message, layout []string) string {

	segments := []string{}

	for _, name := range layout {
		segment := msg.Segment(name)
		if segment == nil {
			continue
		}

		segments = append(segments, message.CreateHL7(segment, name))
	}

	return strings.Join(segments, message.SegmentSeparator)
}

func LinesFromFile(s string) []string {
	return message.SplitSegments(s)
}

// Remove 'null' segments for easier JSON display
func SanitizeLines(lines string) string {
	split := strings.Split(lines, "\n")

	var newLines []string

	for _, line := range split {
		if !strings.Contains(line, ": null") {
			newLines = append(newLines, line)
		}
	}

	join := strings.Join(newLines, "\n")

	return join
}
